name: CI
on:
  repository_dispatch:
    types: [containerregistry-imagepushedc]
    
# CONFIGURATION
# Set up the following secrets in your repository:
#
#   CLUST_NAME
#   RESOURCE_GROUP
env:
   CLUST_NAME: clust               #set this to your kubernetes cluster name
   RESOURCE_GROUP: tryac    #set this to your resource group name
   HOST_NAME: ${{ github.event.client_payload.data.request.host }}
   REPO_NAME: "${{ github.event.client_payload.data.request.host }}/${{ github.event.client_payload.data.target.repository }}"
   REPO_VERSION: "${{ github.event.client_payload.data.target.tag }}"
   IMAGE_NAME: "${{ github.event.client_payload.data.request.host }}/${{ github.event.client_payload.data.target.repository }}:${{ github.event.client_payload.data.target.tag }}"

   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    #- name: Check tag filter
     # run: |
      #  if [ "$repo_version" != "$filter" ]; then echo "incorrect tag filter supplied"; exit 1 ; fi;
          
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.HOST_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'node-rnc'
        images: "${{ env.IMAGE_NAME }}"
